baseurl: ''

title: B Whiting Designs
tagline: I create detailed, custom, modern high-quality designs for your brand needs
description: Freelance UI/UX Designer and Front-end Dev with over 10 years of experience based in Colorado. East coast designer living on the West coast.
url: https://www.bwhitingdesigns.com
author: Brian Whiting
email: brianwhiting@bwhitingdesigns.com
home: https://www.bwhitingdesigns.com
tel: 334-538-5644
tel_link: +13345385644

hosting_url: http://hosting.bwhitingdesigns.com

logo: /images/my-logo.png

google_tag: GTM-NKS3CNF

address: Aurora, CO
timezone: America/Denver

# social settings
blog_url: https://blog.bwhitingdesigns.com
twitch_url: https://www.twitch.tv/forsakenelite08
dribbble_url: https://dribbble.com/BrianWhiting
github_url: https://github.com/bwhitingdesigns
github_username: bwhitingdesigns
facebook_url: https://www.facebook.com/bwhitingdesigns
facebook:
  app_id: 2358622077775061
googleplus_url:
instagram_url: https://www.instagram.com/bwhitingdesigns/
linkedin_url: https://www.linkedin.com/in/bwdesigns/
twitter_url: https://twitter.com/ForsakenElite08
twitter:
  username: ForsakenElite08
  card: summary

# plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-webp

# exclude settings
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

# markdown format
markdown: kramdown

# blog post permalink structure
permalink: /blog/:categories/:title

# collection settings
collections:
  portfolio:
    permalink: "/portfolio/:name"
    output: true
  authors:
    output: true
  category:
    output: true

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# image compression for webp
webp:
  enabled: true
  quality: 60
  img_dir: ["/images"]
  nested: true
  formats: [".jpeg", ".jpg", ".png"]
  gifs: [".gif"]
  regenerate: false
  webp_path: nil
  exclude: []
  append_ext: false