backend:
  name: git-gateway
  branch: master

site_url: https://www.bwhitingdesigns.com
display_url: https://www.bwhitingdesigns.com
logo_url: https://www.bwhitingdesigns.com/images/my-logo.png
publish_mode: editorial_workflow
media_folder: images
public_folder: /images
collections:
  - name: posts
    label: Blog Posts
    label_singular: 'Blog Post'
    folder: _posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Template
        name: template
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
      - label: Permalink
        name: permalink
        widget: string
        required: true
      - label: 'Cover Image'
        name: 'featured_image'
        widget: 'image'
        required: true
      - label: Publish Date
        name: date
        widget: datetime
      - label: Excerpt
        name: preview
        widget: text
      - label: Category
        name: categories
        widget: list
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
  - name: portfolio
    label: Portfolio
    label_singular: 'Portfolio'
    folder: _portfolio
    create: true
    slug: '{{slug}}'
    fields:
      - label: Template
        name: template
        widget: hidden
        default: folio-single
      - label: Title
        name: title
        widget: string
      - label: Permalink
        name: permalink
        widget: string
        default: /:collection/
      - label: Short Name
        name: preview_title
        widget: string
      - label: Client
        name: client
        widget: string
      - label: 'Cover Image'
        name: 'image_preview'
        widget: 'image'
        required: true
      - label: 'Carousel Slide: 1'
        name: 'slide_1'
        widget: 'image'
        required: true
      - label: 'Carousel Caption: 1'
        name: slide_1_caption
        widget: text
        required: true
      - label: Mini Caption
        name: mini_caption
        widget: text
        required: true
      - label: 'Carousel Slide: 2'
        name: 'slide_2'
        widget: 'image'
      - label: 'Carousel Slide: 3'
        name: 'slide_3'
        widget: 'image'
      - label: 'Folio Grid Image'
        name: 'header_image'
        widget: 'image'
        required: true
      - label: 'Company Logo'
        name: 'logo'
        widget: 'image'
      - label: Tagline
        name: tagline
        widget: string
      - label: Main paragraph
        name: intro
        widget: text
        required: true
      - label: 'Heading 1: Title' 
        name: header_1
        widget: string
      - label: 'Heading 1: Content'
        name: header_1_content
        widget: text
      - label: 'Heading 2: Title'
        name: header_2
        widget: string
      - label: 'Heading 2: Content'
        name: header_2_content
        widget: text
      - label: 'Heading 3: Title'
        name: header_3
        widget: string
      - label: 'Heading 3: Content'
        name: header_3_content
        widget: text
      - label: Category
        name: category
        widget: list
      - label: Tags
        name: tag
        widget: list
      - label: Services
        name: services
        widget: list
      - label: Programs
        name: programs
        widget: list
      - label: Location
        name: location
        widget: string
      - label: Live Site
        name: live_url
        widget: string
      - label: Site Name
        name: live_text
        widget: string
      - label: Date Completed
        name: completed
        widget: datetime